package com.springbootgs.springbootgradesubmissionapi.entity;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity // Telling Spring Boot JPA to create a (student) table that stores student entities 
@Table(name = "student") // Name the table
@Getter // Lombok-enabled - generates getters based on defined fields
@Setter // Lombok-enabled - generates
@AllArgsConstructor
@NoArgsConstructor
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "name", nullable = false)
    private String name;
    @Column(name = "birth_date", nullable = false)
    private LocalDate birthDate;

    // Constructor with all fields - generated with Lombok's @AllArgsContructor
    // public Student(Long id, String name, LocalDate birthDate) {
    //     this.id = id;
    //     this.name = name;
    //     this.birthDate = birthDate;
    // }
    
    // Empty constructor - generated by Lombok's @NoArgsConstructor
    // public Student() {
    // }

}